### ISSUE TITLE
[Android Client Todo] 添加更新通道选项

### ISSUE THREAD

**Issue by MoonBegonia** [DUpdateSystem/UpgradeAll#11]
**描述新功能或计划**
添加；类似于 magisk 的更新通道选项

**添加该功能的原因**
默认 `master` 通道和 `dev` 切换麻烦

**实现方法**

**描述这个变动涉及的模块**
ui

**该功能是否需要服务端变动**
否

**相关的 issues**
无

**优先级**
低

**开发状态**
Todo

**Comment by xz-dev** [comment]
功能已通过“可选择调用服务更新服务器获取云端配置”的方式实现 https://github.com/DUpdateSystem/UpgradeAll/commit/8693b7a663b2c6fc4ddc31b1830d9aaafc6e01be
