### ISSUE TITLE
[enhancement] maintain an F-Droid repo with Apps already in the rules repo

### ISSUE THREAD

**Issue by momobobe** [DUpdateSystem/UpgradeAll#177]
Besides the update server for UpgradeAll, also host an F-Droid repo with same (or maybe some filtered) Apps inside. This wouldn't consume many extra resources, and could bring some more F-Droid users here (at least have more of them aware of this project), which should be a nice way for promotion.

**Comment by xz-dev** [comment]
Good idea but hard to realize if you know how the APP work, because we can not scan a whole site such as google play.

**Comment by xz-dev** [comment]
@momobobe you are right
