### ISSUE TITLE
[enhancement or bug report] expected behavior regarding Root

### ISSUE THREAD

**Issue by momobobe** [DUpdateSystem/UpgradeAll#180]
Currently the App always requests Root privilege upon open, no matter whether the APK installation method is set to Root. The expected behavior should be, only requesting Root privilege when it's set to Root, and not bothering to ask for that if users have set it to System Installer or Shizuku

**Comment by xz-dev** [comment]
https://github.com/DUpdateSystem/UpgradeAll/commit/96f4bf7d1b2ecc0e822a06a19bcc4716edf8acf1
