### ISSUE TITLE
[enhancement or bug report] change default url for rule repo and update server

### ISSUE THREAD

**Issue by momobobe** [DUpdateSystem/UpgradeAll#182]
The default update server `update-server.xzos.net` is pretty inaccessible for international users in most time, and since the default setting for rule repo is "Follow Server Config", new users have a great chance to load nothing without knowledge of alternative links, which is very user-unfriendly and hence makes most new users lose interest in further use.

So please add the links [Coding (For China Mainland)](https://dupdatesystem.coding.net/p/UpgradeAll-rules/d/UpgradeAll-rules/git/raw/master/rules/rules.json), [Jsdelivr CDN (Recommanded for areas which cant access Github well)](https://cdn.jsdelivr.net/gh/DUpdateSystem/UpgradeAll-rules@master/rules/rules.json), [GitHub](https://raw.githubusercontent.com/DUpdateSystem/UpgradeAll-rules/master/rules/rules.json) listed in FAQ as built-in options for users to select (preferably a prompt should display upon first-time open as tutorials, and the tutorials could further cover the content [there](https://up-a.org/en/guide/)).

Also, please do something to make the default update server `update-server.xzos.net` more accessible for international users, though AFAIK Internet condition in China is quite frightening. Maybe you can introduce some CDN stuff to it just like the main site `xzos.net`. Or host a new server at `up-a.org` (even on GitHub if feasible).

**Comment by xz-dev** [comment]
The server is not serving static content, but in the next version the problem will be solove

**Comment by xz-dev** [comment]
Update service has been shutdown, all server function move back to client.
