### ISSUE TITLE
[enhancement] 自定义下载链接

### ISSUE THREAD

**Issue by banbendalao** [DUpdateSystem/UpgradeAll#19]
**描述新功能或计划**
允许替换软件下载链接

**添加该功能的原因**
解决github等软件源下载过慢的问题

**实现方法或步骤**

1. 
2. 
3. 

**该变动涉及的模块**

**该功能是否需要其他平台项目变动**

**优先级**

**开发状态**

**相关的 issues**

**Comment by xz-dev** [comment]
已完成
