### ISSUE TITLE
Add support for Gitlab's "tags"

### ISSUE THREAD

**Issue by TsukihiAraragi** [DUpdateSystem/UpgradeAll#2]
Same to GitHub's "Release", Gitlab has a "tags" to release bin files etc. Can you add it? If you'd add it, there is a project you can test it on Gitlab: https://gitlab.com/AuroraOSS/auroradroid/-/tags

**Comment by xz-dev** [comment]
This looks good, I will test it and support it. However, UpgradeAll also supports custom configuration for different depots. In order to reduce my workload, I will use this method instead of Gitlab's API unless you can prove that API is more stable.

**Comment by xz-dev** [comment]
This looks good, I will test it and support it. However, UpgradeAll also supports custom configuration for different depots. In order to reduce my workload, I will use this method.

**Comment by xz-dev** [comment]
In the future, I will also support user customization of APIs for different websites.

**Comment by xz-dev** [comment]
In the future, I will also support users to configure their own API.

**Comment by wangxiaoerYah** [comment]
> Same to GitHub's "Release", Gitlab has a "tags" to release bin files etc. Can you add it? If you'd add it, there is a project you can test it on Gitlab: https://gitlab.com/AuroraOSS/auroradroid/-/tags

Neither gitlab's HTML nor the api supports crawling.  And found that most projects on gitlab only release source code.  May be meaningless.  So far I have not found a better way to get gitlab data.  Can you provide more TAG pages?  Contains a release page for the executable.

**Comment by TsukihiAraragi** [comment]
@wangxiaoerYah Right, many repos only provide source code, and now, somebody release files in "tags", somebody in "releases".
here's some GitLab repos: 
[AuroraStore](https://gitlab.com/AuroraOSS/AuroraStore) [oandbackup](https://gitlab.com/jensstein/oandbackup/-/tags)
[Feeder](https://gitlab.com/spacecowboy/Feeder)

**Comment by wangxiaoerYah** [comment]
> @wangxiaoerYah Right, many repos only provide source code, and now, somebody release files in "tags", somebody in "releases".
> here's some GitLab repos:
> [AuroraStore](https://gitlab.com/AuroraOSS/AuroraStore) [oandbackup](https://gitlab.com/jensstein/oandbackup/-/tags)
> [Feeder](https://gitlab.com/spacecowboy/Feeder)

Of these three projects, only "aurorastore" has released executables.  If it is only for projects that publish software through changelog, that's fine.  We have made it and we are discussing whether to release it.  Because there are few projects using gitlab, it is officially defined as a private backup repository and does not support publishing binary files.  I don't think it makes sense, but if you want support, you will see it in the next rules dev branch.

**Comment by wangxiaoerYah** [comment]
> @wangxiaoerYah Right, many repos only provide source code, and now, somebody release files in "tags", somebody in "releases".
> here's some GitLab repos:
> [AuroraStore](https://gitlab.com/AuroraOSS/AuroraStore) [oandbackup](https://gitlab.com/jensstein/oandbackup/-/tags)
> [Feeder](https://gitlab.com/spacecowboy/Feeder)

https://github.com/DUpdateSystem/UpgradeAll-rules

**Comment by xz-dev** [comment]
已支持
