### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by webmaster-exit-1** [DUpdateSystem/UpgradeAll#412]
Why doesn't this app scan the installed apps then parse that into a list that gets correlated with the appropriate market link for update checking? I'm sure if you threw that into copilot it could accomplish this for you, with minimal effort.

**Comment by xz-dev** [comment]
Thanks for your suggest, but I don't understand how can AI help us.
Can you give me an example?

**Comment by webmaster-exit-1** [comment]
All I meant by that was having AI code it for you. To save you time. If you don't already use something like github's copilot or OpenDevin then I'm sorry for confusing you.

**Comment by xz-dev** [comment]
> All I meant by that was having AI code it for you. To save you time. If you don't already use something like github's copilot or OpenDevin then I'm sorry for confusing you.

I got it.
And the reason why not auto-detect APP is a lot of API (such as GitHub) have rate limit.
