### ISSUE TITLE
云端仓库无法使用（已按WIKI操作，仍无法使用）

### ISSUE THREAD

**Issue by zaonie** [DUpdateSystem/UpgradeAll#7]
华为荣耀8C安卓8.1.0.
UpgradeAll已给全部权限+添加信任。
手机没安FQ工具，但是可以流畅裸连GITHUB。联通WIFI和4G都是。
经过检查您WIKI里“添加软件源”https://github.com/DUpdateSystem/UpgradeAll/wiki/%E6%B7%BB%E5%8A%A0%E8%BD%AF%E4%BB%B6%E6%BA%90 的步骤，
验证仓库地址无误，仍然无法使用软件源。
日志为CloudConfigGetterE/ OkHttpApi: get HttpResponse:网络错误。

**Comment by xz-dev** [comment]
[国内镜像](https://dupdatesystem.coding.net/p/UpgradeAll-rules/d/UpgradeAll-rules/git/tree/dev)已开始内测
请等待正式版更新
或加入用户群获取内测版本

感谢您对本软件的关注与支持！
