### ISSUE TITLE
[Enhancent] Add option to check app details in discover before downloading. 

### ISSUE THREAD

**Issue by shom13** [DUpdateSystem/UpgradeAll#79]
Add option to check the app or view about app before downloding it. I am not sure if this has already been requested or not because of language barrier.

**Comment by JohnsonRan** [comment]
@shom13 @xz-dev

**Comment by xz-dev** [comment]
@shom13 I will code for it tomorrow. I guess you want to see the information of APPs in discover page?

**Comment by shom13** [comment]
Yes, that would be really helpful.  Thank you

**Comment by xz-dev** [comment]
I add url and id in download dialog, I'm not sure if you want the display method of Lsposed. https://github.com/DUpdateSystem/UpgradeAll/commit/12bb1d83ee38338b14c670245639c89a34eaee6c
You can download CI apk in tg channel. https://t.me/upallci

**Comment by xz-dev** [comment]
@shom13 The office service was down, I'm trying to fix it.

**Comment by shom13** [comment]
Oh ok. Thank you for the update

**Comment by JohnsonRan** [comment]
@shom13 Our update server is online now. Sorry for waiting!

**Comment by xz-dev** [comment]
I had optimized interface display. https://github.com/DUpdateSystem/UpgradeAll/commit/2232bdd4f802488d5b5ed15171096fc6fcc5dfca
You can try the newest CI and tell me if this is what you want.

**Comment by shom13** [comment]
Yes new one is helpful, but the link provided is not clickable. If you could make it clickable then one could click on the provided link and find some information about the app before downloading it. Thanks

**Comment by xz-dev** [comment]
I fixed it in the newest CI.

**Comment by shom13** [comment]
Thank you so much. Really appreciate it. Where can i find the new version

**Comment by JohnsonRan** [comment]
@shom13 t.me/upallci

**Comment by shom13** [comment]
I can confirm its works now. Thank you so much

**Comment by xz-dev** [comment]
@shom13 So I want to confirm again, that's all you need?

**Comment by shom13** [comment]
Yes this is exactly what i wanted

**Comment by xz-dev** [comment]
Great, thank you for your suggestion.
